from dataclasses import dataclass


@dataclass(frozen=True)
class InfrastructureResult:
    provider: str
    status: str
    external_id: str | None = None
    ip_address: str | None = None
    note: str = ""


class SimulatedVmProvider:
    provider_name = "simulated-vm"

    def start_machine(self, machine, session) -> InfrastructureResult:
        machine_code = getattr(machine, "code", "cloud-rig")
        return InfrastructureResult(
            provider=self.provider_name,
            status="running",
            external_id=f"sim-vm-{machine_code}-{str(session.id)[:8]}",
            note="VM lifecycle is simulated for the graduation prototype.",
        )

    def stop_machine(self, machine, session) -> InfrastructureResult:
        machine_code = getattr(machine, "code", "cloud-rig")
        return InfrastructureResult(
            provider=self.provider_name,
            status="stopped",
            external_id=f"sim-vm-{machine_code}-{str(session.id)[:8]}",
            note="Replace this adapter with Proxmox, AWS, or another VM provider in production.",
        )


class SimulatedVpnProvider:
    provider_name = "simulated-openvpn"

    def create_profile(self, machine, session) -> InfrastructureResult:
        return InfrastructureResult(
            provider=self.provider_name,
            status="profile_ready",
            external_id=f"ovpn-{str(session.id)[:8]}",
            note="OpenVPN profile content is generated by the backend; tunnel detection is simulated.",
        )

    def check_connection(self, machine, session) -> InfrastructureResult:
        return InfrastructureResult(
            provider=self.provider_name,
            status="connected",
            external_id=f"route-{str(session.id)[:8]}",
            ip_address=self.assign_local_ip(session),
            note="In production this should read the VPN lease table or gateway session API.",
        )

    def assign_local_ip(self, session) -> str:
        host_octet = (session.id.int % 230) + 20
        return f"10.8.0.{host_octet}"


class SimulatedStreamingProvider:
    provider_name = "simulated-sunshine-moonlight"

    def mark_ready(self, machine, session) -> InfrastructureResult:
        machine_code = getattr(machine, "code", "cloud-rig")
        return InfrastructureResult(
            provider=self.provider_name,
            status="ready",
            external_id=f"stream-{machine_code}-{str(session.id)[:8]}",
            note="Pairing is confirmed by the user; a real build should call Sunshine/Moonlight APIs.",
        )
